//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 09:45:50 AM CDT 
//


package com.tikal.cacao.sat.cfd.catalogos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_Aduana.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_Aduana">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="01"/>
 *     &lt;enumeration value="02"/>
 *     &lt;enumeration value="05"/>
 *     &lt;enumeration value="06"/>
 *     &lt;enumeration value="07"/>
 *     &lt;enumeration value="08"/>
 *     &lt;enumeration value="11"/>
 *     &lt;enumeration value="12"/>
 *     &lt;enumeration value="14"/>
 *     &lt;enumeration value="16"/>
 *     &lt;enumeration value="17"/>
 *     &lt;enumeration value="18"/>
 *     &lt;enumeration value="19"/>
 *     &lt;enumeration value="20"/>
 *     &lt;enumeration value="22"/>
 *     &lt;enumeration value="23"/>
 *     &lt;enumeration value="24"/>
 *     &lt;enumeration value="25"/>
 *     &lt;enumeration value="26"/>
 *     &lt;enumeration value="27"/>
 *     &lt;enumeration value="28"/>
 *     &lt;enumeration value="30"/>
 *     &lt;enumeration value="31"/>
 *     &lt;enumeration value="33"/>
 *     &lt;enumeration value="34"/>
 *     &lt;enumeration value="37"/>
 *     &lt;enumeration value="38"/>
 *     &lt;enumeration value="39"/>
 *     &lt;enumeration value="40"/>
 *     &lt;enumeration value="42"/>
 *     &lt;enumeration value="43"/>
 *     &lt;enumeration value="44"/>
 *     &lt;enumeration value="46"/>
 *     &lt;enumeration value="47"/>
 *     &lt;enumeration value="48"/>
 *     &lt;enumeration value="50"/>
 *     &lt;enumeration value="51"/>
 *     &lt;enumeration value="52"/>
 *     &lt;enumeration value="53"/>
 *     &lt;enumeration value="64"/>
 *     &lt;enumeration value="65"/>
 *     &lt;enumeration value="67"/>
 *     &lt;enumeration value="73"/>
 *     &lt;enumeration value="75"/>
 *     &lt;enumeration value="80"/>
 *     &lt;enumeration value="81"/>
 *     &lt;enumeration value="82"/>
 *     &lt;enumeration value="83"/>
 *     &lt;enumeration value="84"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_Aduana", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")
@XmlEnum
public enum C_Aduana {

    @XmlEnumValue("01")
    VALUE_1("01"),
    @XmlEnumValue("02")
    VALUE_2("02"),
    @XmlEnumValue("05")
    VALUE_3("05"),
    @XmlEnumValue("06")
    VALUE_4("06"),
    @XmlEnumValue("07")
    VALUE_5("07"),
    @XmlEnumValue("08")
    VALUE_6("08"),
    @XmlEnumValue("11")
    VALUE_7("11"),
    @XmlEnumValue("12")
    VALUE_8("12"),
    @XmlEnumValue("14")
    VALUE_9("14"),
    @XmlEnumValue("16")
    VALUE_10("16"),
    @XmlEnumValue("17")
    VALUE_11("17"),
    @XmlEnumValue("18")
    VALUE_12("18"),
    @XmlEnumValue("19")
    VALUE_13("19"),
    @XmlEnumValue("20")
    VALUE_14("20"),
    @XmlEnumValue("22")
    VALUE_15("22"),
    @XmlEnumValue("23")
    VALUE_16("23"),
    @XmlEnumValue("24")
    VALUE_17("24"),
    @XmlEnumValue("25")
    VALUE_18("25"),
    @XmlEnumValue("26")
    VALUE_19("26"),
    @XmlEnumValue("27")
    VALUE_20("27"),
    @XmlEnumValue("28")
    VALUE_21("28"),
    @XmlEnumValue("30")
    VALUE_22("30"),
    @XmlEnumValue("31")
    VALUE_23("31"),
    @XmlEnumValue("33")
    VALUE_24("33"),
    @XmlEnumValue("34")
    VALUE_25("34"),
    @XmlEnumValue("37")
    VALUE_26("37"),
    @XmlEnumValue("38")
    VALUE_27("38"),
    @XmlEnumValue("39")
    VALUE_28("39"),
    @XmlEnumValue("40")
    VALUE_29("40"),
    @XmlEnumValue("42")
    VALUE_30("42"),
    @XmlEnumValue("43")
    VALUE_31("43"),
    @XmlEnumValue("44")
    VALUE_32("44"),
    @XmlEnumValue("46")
    VALUE_33("46"),
    @XmlEnumValue("47")
    VALUE_34("47"),
    @XmlEnumValue("48")
    VALUE_35("48"),
    @XmlEnumValue("50")
    VALUE_36("50"),
    @XmlEnumValue("51")
    VALUE_37("51"),
    @XmlEnumValue("52")
    VALUE_38("52"),
    @XmlEnumValue("53")
    VALUE_39("53"),
    @XmlEnumValue("64")
    VALUE_40("64"),
    @XmlEnumValue("65")
    VALUE_41("65"),
    @XmlEnumValue("67")
    VALUE_42("67"),
    @XmlEnumValue("73")
    VALUE_43("73"),
    @XmlEnumValue("75")
    VALUE_44("75"),
    @XmlEnumValue("80")
    VALUE_45("80"),
    @XmlEnumValue("81")
    VALUE_46("81"),
    @XmlEnumValue("82")
    VALUE_47("82"),
    @XmlEnumValue("83")
    VALUE_48("83"),
    @XmlEnumValue("84")
    VALUE_49("84");
    private final String value;

    C_Aduana(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_Aduana fromValue(String v) {
        for (C_Aduana c: C_Aduana.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
