//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 09:45:50 AM CDT 
//


package com.tikal.cacao.sat.cfd.catalogos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

import com.google.gson.annotations.SerializedName;


/**
 * <p>Java class for c_FormaPago.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_FormaPago">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="01"/>
 *     &lt;enumeration value="02"/>
 *     &lt;enumeration value="03"/>
 *     &lt;enumeration value="04"/>
 *     &lt;enumeration value="05"/>
 *     &lt;enumeration value="06"/>
 *     &lt;enumeration value="08"/>
 *     &lt;enumeration value="12"/>
 *     &lt;enumeration value="13"/>
 *     &lt;enumeration value="14"/>
 *     &lt;enumeration value="15"/>
 *     &lt;enumeration value="17"/>
 *     &lt;enumeration value="23"/>
 *     &lt;enumeration value="24"/>
 *     &lt;enumeration value="25"/>
 *     &lt;enumeration value="26"/>
 *     &lt;enumeration value="27"/>
 *     &lt;enumeration value="28"/>
 *     &lt;enumeration value="29"/>
 *     &lt;enumeration value="99"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_FormaPago", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")
@XmlEnum
public enum C_FormaPago {

    @XmlEnumValue("01")
    VALUE_1("01"),
    @XmlEnumValue("02")
    VALUE_2("02"),
    @XmlEnumValue("03")
    VALUE_3("03"),
    @XmlEnumValue("04")
    VALUE_4("04"),
    @XmlEnumValue("05")
    VALUE_5("05"),
    @XmlEnumValue("06")
    VALUE_6("06"),
    @XmlEnumValue("08")
    VALUE_7("08"),
    @XmlEnumValue("12")
    VALUE_8("12"),
    @XmlEnumValue("13")
    VALUE_9("13"),
    @XmlEnumValue("14")
    VALUE_10("14"),
    @XmlEnumValue("15")
    VALUE_11("15"),
    @XmlEnumValue("17")
    VALUE_12("17"),
    @XmlEnumValue("23")
    VALUE_13("23"),
    @XmlEnumValue("24")
    VALUE_14("24"),
    @XmlEnumValue("25")
    VALUE_15("25"),
    @XmlEnumValue("26")
    VALUE_16("26"),
    @XmlEnumValue("27")
    VALUE_17("27"),
    @XmlEnumValue("28")
    VALUE_18("28"),
    @XmlEnumValue("29")
    VALUE_19("29"),
    @SerializedName("Por definir")
    @XmlEnumValue("99")
    VALUE_20("99");
    private final String value;

    C_FormaPago(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_FormaPago fromValue(String v) {
        for (C_FormaPago c: C_FormaPago.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
