//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 09:45:50 AM CDT 
//


package com.tikal.cacao.sat.cfd.catalogos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_Localidad.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_Localidad">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="01"/>
 *     &lt;enumeration value="02"/>
 *     &lt;enumeration value="03"/>
 *     &lt;enumeration value="04"/>
 *     &lt;enumeration value="05"/>
 *     &lt;enumeration value="06"/>
 *     &lt;enumeration value="07"/>
 *     &lt;enumeration value="08"/>
 *     &lt;enumeration value="09"/>
 *     &lt;enumeration value="10"/>
 *     &lt;enumeration value="11"/>
 *     &lt;enumeration value="12"/>
 *     &lt;enumeration value="13"/>
 *     &lt;enumeration value="14"/>
 *     &lt;enumeration value="15"/>
 *     &lt;enumeration value="16"/>
 *     &lt;enumeration value="17"/>
 *     &lt;enumeration value="18"/>
 *     &lt;enumeration value="19"/>
 *     &lt;enumeration value="20"/>
 *     &lt;enumeration value="21"/>
 *     &lt;enumeration value="22"/>
 *     &lt;enumeration value="23"/>
 *     &lt;enumeration value="24"/>
 *     &lt;enumeration value="25"/>
 *     &lt;enumeration value="26"/>
 *     &lt;enumeration value="27"/>
 *     &lt;enumeration value="28"/>
 *     &lt;enumeration value="29"/>
 *     &lt;enumeration value="30"/>
 *     &lt;enumeration value="31"/>
 *     &lt;enumeration value="32"/>
 *     &lt;enumeration value="33"/>
 *     &lt;enumeration value="34"/>
 *     &lt;enumeration value="35"/>
 *     &lt;enumeration value="36"/>
 *     &lt;enumeration value="37"/>
 *     &lt;enumeration value="38"/>
 *     &lt;enumeration value="39"/>
 *     &lt;enumeration value="40"/>
 *     &lt;enumeration value="41"/>
 *     &lt;enumeration value="42"/>
 *     &lt;enumeration value="43"/>
 *     &lt;enumeration value="44"/>
 *     &lt;enumeration value="45"/>
 *     &lt;enumeration value="46"/>
 *     &lt;enumeration value="47"/>
 *     &lt;enumeration value="48"/>
 *     &lt;enumeration value="49"/>
 *     &lt;enumeration value="50"/>
 *     &lt;enumeration value="51"/>
 *     &lt;enumeration value="52"/>
 *     &lt;enumeration value="53"/>
 *     &lt;enumeration value="54"/>
 *     &lt;enumeration value="55"/>
 *     &lt;enumeration value="56"/>
 *     &lt;enumeration value="57"/>
 *     &lt;enumeration value="58"/>
 *     &lt;enumeration value="59"/>
 *     &lt;enumeration value="60"/>
 *     &lt;enumeration value="61"/>
 *     &lt;enumeration value="62"/>
 *     &lt;enumeration value="66"/>
 *     &lt;enumeration value="67"/>
 *     &lt;enumeration value="68"/>
 *     &lt;enumeration value="69"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_Localidad", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")
@XmlEnum
public enum C_Localidad {

    @XmlEnumValue("01")
    VALUE_1("01"),
    @XmlEnumValue("02")
    VALUE_2("02"),
    @XmlEnumValue("03")
    VALUE_3("03"),
    @XmlEnumValue("04")
    VALUE_4("04"),
    @XmlEnumValue("05")
    VALUE_5("05"),
    @XmlEnumValue("06")
    VALUE_6("06"),
    @XmlEnumValue("07")
    VALUE_7("07"),
    @XmlEnumValue("08")
    VALUE_8("08"),
    @XmlEnumValue("09")
    VALUE_9("09"),
    @XmlEnumValue("10")
    VALUE_10("10"),
    @XmlEnumValue("11")
    VALUE_11("11"),
    @XmlEnumValue("12")
    VALUE_12("12"),
    @XmlEnumValue("13")
    VALUE_13("13"),
    @XmlEnumValue("14")
    VALUE_14("14"),
    @XmlEnumValue("15")
    VALUE_15("15"),
    @XmlEnumValue("16")
    VALUE_16("16"),
    @XmlEnumValue("17")
    VALUE_17("17"),
    @XmlEnumValue("18")
    VALUE_18("18"),
    @XmlEnumValue("19")
    VALUE_19("19"),
    @XmlEnumValue("20")
    VALUE_20("20"),
    @XmlEnumValue("21")
    VALUE_21("21"),
    @XmlEnumValue("22")
    VALUE_22("22"),
    @XmlEnumValue("23")
    VALUE_23("23"),
    @XmlEnumValue("24")
    VALUE_24("24"),
    @XmlEnumValue("25")
    VALUE_25("25"),
    @XmlEnumValue("26")
    VALUE_26("26"),
    @XmlEnumValue("27")
    VALUE_27("27"),
    @XmlEnumValue("28")
    VALUE_28("28"),
    @XmlEnumValue("29")
    VALUE_29("29"),
    @XmlEnumValue("30")
    VALUE_30("30"),
    @XmlEnumValue("31")
    VALUE_31("31"),
    @XmlEnumValue("32")
    VALUE_32("32"),
    @XmlEnumValue("33")
    VALUE_33("33"),
    @XmlEnumValue("34")
    VALUE_34("34"),
    @XmlEnumValue("35")
    VALUE_35("35"),
    @XmlEnumValue("36")
    VALUE_36("36"),
    @XmlEnumValue("37")
    VALUE_37("37"),
    @XmlEnumValue("38")
    VALUE_38("38"),
    @XmlEnumValue("39")
    VALUE_39("39"),
    @XmlEnumValue("40")
    VALUE_40("40"),
    @XmlEnumValue("41")
    VALUE_41("41"),
    @XmlEnumValue("42")
    VALUE_42("42"),
    @XmlEnumValue("43")
    VALUE_43("43"),
    @XmlEnumValue("44")
    VALUE_44("44"),
    @XmlEnumValue("45")
    VALUE_45("45"),
    @XmlEnumValue("46")
    VALUE_46("46"),
    @XmlEnumValue("47")
    VALUE_47("47"),
    @XmlEnumValue("48")
    VALUE_48("48"),
    @XmlEnumValue("49")
    VALUE_49("49"),
    @XmlEnumValue("50")
    VALUE_50("50"),
    @XmlEnumValue("51")
    VALUE_51("51"),
    @XmlEnumValue("52")
    VALUE_52("52"),
    @XmlEnumValue("53")
    VALUE_53("53"),
    @XmlEnumValue("54")
    VALUE_54("54"),
    @XmlEnumValue("55")
    VALUE_55("55"),
    @XmlEnumValue("56")
    VALUE_56("56"),
    @XmlEnumValue("57")
    VALUE_57("57"),
    @XmlEnumValue("58")
    VALUE_58("58"),
    @XmlEnumValue("59")
    VALUE_59("59"),
    @XmlEnumValue("60")
    VALUE_60("60"),
    @XmlEnumValue("61")
    VALUE_61("61"),
    @XmlEnumValue("62")
    VALUE_62("62"),
    @XmlEnumValue("66")
    VALUE_63("66"),
    @XmlEnumValue("67")
    VALUE_64("67"),
    @XmlEnumValue("68")
    VALUE_65("68"),
    @XmlEnumValue("69")
    VALUE_66("69");
    private final String value;

    C_Localidad(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_Localidad fromValue(String v) {
        for (C_Localidad c: C_Localidad.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
