//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 09:45:50 AM CDT 
//


package com.tikal.cacao.sat.cfd.catalogos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_Municipio.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_Municipio">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="001"/>
 *     &lt;enumeration value="002"/>
 *     &lt;enumeration value="003"/>
 *     &lt;enumeration value="004"/>
 *     &lt;enumeration value="005"/>
 *     &lt;enumeration value="006"/>
 *     &lt;enumeration value="007"/>
 *     &lt;enumeration value="008"/>
 *     &lt;enumeration value="009"/>
 *     &lt;enumeration value="010"/>
 *     &lt;enumeration value="011"/>
 *     &lt;enumeration value="012"/>
 *     &lt;enumeration value="013"/>
 *     &lt;enumeration value="014"/>
 *     &lt;enumeration value="015"/>
 *     &lt;enumeration value="016"/>
 *     &lt;enumeration value="017"/>
 *     &lt;enumeration value="018"/>
 *     &lt;enumeration value="019"/>
 *     &lt;enumeration value="020"/>
 *     &lt;enumeration value="021"/>
 *     &lt;enumeration value="022"/>
 *     &lt;enumeration value="023"/>
 *     &lt;enumeration value="024"/>
 *     &lt;enumeration value="025"/>
 *     &lt;enumeration value="026"/>
 *     &lt;enumeration value="027"/>
 *     &lt;enumeration value="028"/>
 *     &lt;enumeration value="029"/>
 *     &lt;enumeration value="030"/>
 *     &lt;enumeration value="031"/>
 *     &lt;enumeration value="032"/>
 *     &lt;enumeration value="033"/>
 *     &lt;enumeration value="034"/>
 *     &lt;enumeration value="035"/>
 *     &lt;enumeration value="036"/>
 *     &lt;enumeration value="037"/>
 *     &lt;enumeration value="038"/>
 *     &lt;enumeration value="039"/>
 *     &lt;enumeration value="040"/>
 *     &lt;enumeration value="041"/>
 *     &lt;enumeration value="042"/>
 *     &lt;enumeration value="043"/>
 *     &lt;enumeration value="044"/>
 *     &lt;enumeration value="045"/>
 *     &lt;enumeration value="046"/>
 *     &lt;enumeration value="047"/>
 *     &lt;enumeration value="048"/>
 *     &lt;enumeration value="049"/>
 *     &lt;enumeration value="050"/>
 *     &lt;enumeration value="051"/>
 *     &lt;enumeration value="052"/>
 *     &lt;enumeration value="053"/>
 *     &lt;enumeration value="054"/>
 *     &lt;enumeration value="055"/>
 *     &lt;enumeration value="056"/>
 *     &lt;enumeration value="057"/>
 *     &lt;enumeration value="058"/>
 *     &lt;enumeration value="059"/>
 *     &lt;enumeration value="060"/>
 *     &lt;enumeration value="061"/>
 *     &lt;enumeration value="062"/>
 *     &lt;enumeration value="063"/>
 *     &lt;enumeration value="064"/>
 *     &lt;enumeration value="065"/>
 *     &lt;enumeration value="066"/>
 *     &lt;enumeration value="067"/>
 *     &lt;enumeration value="068"/>
 *     &lt;enumeration value="069"/>
 *     &lt;enumeration value="070"/>
 *     &lt;enumeration value="071"/>
 *     &lt;enumeration value="072"/>
 *     &lt;enumeration value="073"/>
 *     &lt;enumeration value="074"/>
 *     &lt;enumeration value="075"/>
 *     &lt;enumeration value="076"/>
 *     &lt;enumeration value="077"/>
 *     &lt;enumeration value="078"/>
 *     &lt;enumeration value="079"/>
 *     &lt;enumeration value="080"/>
 *     &lt;enumeration value="081"/>
 *     &lt;enumeration value="082"/>
 *     &lt;enumeration value="083"/>
 *     &lt;enumeration value="084"/>
 *     &lt;enumeration value="085"/>
 *     &lt;enumeration value="086"/>
 *     &lt;enumeration value="087"/>
 *     &lt;enumeration value="088"/>
 *     &lt;enumeration value="089"/>
 *     &lt;enumeration value="090"/>
 *     &lt;enumeration value="091"/>
 *     &lt;enumeration value="092"/>
 *     &lt;enumeration value="093"/>
 *     &lt;enumeration value="094"/>
 *     &lt;enumeration value="095"/>
 *     &lt;enumeration value="096"/>
 *     &lt;enumeration value="097"/>
 *     &lt;enumeration value="098"/>
 *     &lt;enumeration value="099"/>
 *     &lt;enumeration value="100"/>
 *     &lt;enumeration value="101"/>
 *     &lt;enumeration value="102"/>
 *     &lt;enumeration value="103"/>
 *     &lt;enumeration value="104"/>
 *     &lt;enumeration value="105"/>
 *     &lt;enumeration value="106"/>
 *     &lt;enumeration value="107"/>
 *     &lt;enumeration value="108"/>
 *     &lt;enumeration value="109"/>
 *     &lt;enumeration value="110"/>
 *     &lt;enumeration value="111"/>
 *     &lt;enumeration value="112"/>
 *     &lt;enumeration value="113"/>
 *     &lt;enumeration value="114"/>
 *     &lt;enumeration value="115"/>
 *     &lt;enumeration value="116"/>
 *     &lt;enumeration value="117"/>
 *     &lt;enumeration value="118"/>
 *     &lt;enumeration value="119"/>
 *     &lt;enumeration value="120"/>
 *     &lt;enumeration value="121"/>
 *     &lt;enumeration value="122"/>
 *     &lt;enumeration value="123"/>
 *     &lt;enumeration value="124"/>
 *     &lt;enumeration value="125"/>
 *     &lt;enumeration value="126"/>
 *     &lt;enumeration value="127"/>
 *     &lt;enumeration value="128"/>
 *     &lt;enumeration value="129"/>
 *     &lt;enumeration value="130"/>
 *     &lt;enumeration value="131"/>
 *     &lt;enumeration value="132"/>
 *     &lt;enumeration value="133"/>
 *     &lt;enumeration value="134"/>
 *     &lt;enumeration value="135"/>
 *     &lt;enumeration value="136"/>
 *     &lt;enumeration value="137"/>
 *     &lt;enumeration value="138"/>
 *     &lt;enumeration value="139"/>
 *     &lt;enumeration value="140"/>
 *     &lt;enumeration value="141"/>
 *     &lt;enumeration value="142"/>
 *     &lt;enumeration value="143"/>
 *     &lt;enumeration value="144"/>
 *     &lt;enumeration value="145"/>
 *     &lt;enumeration value="146"/>
 *     &lt;enumeration value="147"/>
 *     &lt;enumeration value="148"/>
 *     &lt;enumeration value="149"/>
 *     &lt;enumeration value="150"/>
 *     &lt;enumeration value="151"/>
 *     &lt;enumeration value="152"/>
 *     &lt;enumeration value="153"/>
 *     &lt;enumeration value="154"/>
 *     &lt;enumeration value="155"/>
 *     &lt;enumeration value="156"/>
 *     &lt;enumeration value="157"/>
 *     &lt;enumeration value="158"/>
 *     &lt;enumeration value="159"/>
 *     &lt;enumeration value="160"/>
 *     &lt;enumeration value="161"/>
 *     &lt;enumeration value="162"/>
 *     &lt;enumeration value="163"/>
 *     &lt;enumeration value="164"/>
 *     &lt;enumeration value="165"/>
 *     &lt;enumeration value="166"/>
 *     &lt;enumeration value="167"/>
 *     &lt;enumeration value="168"/>
 *     &lt;enumeration value="169"/>
 *     &lt;enumeration value="170"/>
 *     &lt;enumeration value="171"/>
 *     &lt;enumeration value="172"/>
 *     &lt;enumeration value="173"/>
 *     &lt;enumeration value="174"/>
 *     &lt;enumeration value="175"/>
 *     &lt;enumeration value="176"/>
 *     &lt;enumeration value="177"/>
 *     &lt;enumeration value="178"/>
 *     &lt;enumeration value="179"/>
 *     &lt;enumeration value="180"/>
 *     &lt;enumeration value="181"/>
 *     &lt;enumeration value="182"/>
 *     &lt;enumeration value="183"/>
 *     &lt;enumeration value="184"/>
 *     &lt;enumeration value="185"/>
 *     &lt;enumeration value="186"/>
 *     &lt;enumeration value="187"/>
 *     &lt;enumeration value="188"/>
 *     &lt;enumeration value="189"/>
 *     &lt;enumeration value="190"/>
 *     &lt;enumeration value="191"/>
 *     &lt;enumeration value="192"/>
 *     &lt;enumeration value="193"/>
 *     &lt;enumeration value="194"/>
 *     &lt;enumeration value="195"/>
 *     &lt;enumeration value="196"/>
 *     &lt;enumeration value="197"/>
 *     &lt;enumeration value="198"/>
 *     &lt;enumeration value="199"/>
 *     &lt;enumeration value="200"/>
 *     &lt;enumeration value="201"/>
 *     &lt;enumeration value="202"/>
 *     &lt;enumeration value="203"/>
 *     &lt;enumeration value="204"/>
 *     &lt;enumeration value="205"/>
 *     &lt;enumeration value="206"/>
 *     &lt;enumeration value="207"/>
 *     &lt;enumeration value="208"/>
 *     &lt;enumeration value="209"/>
 *     &lt;enumeration value="210"/>
 *     &lt;enumeration value="211"/>
 *     &lt;enumeration value="212"/>
 *     &lt;enumeration value="213"/>
 *     &lt;enumeration value="214"/>
 *     &lt;enumeration value="215"/>
 *     &lt;enumeration value="216"/>
 *     &lt;enumeration value="217"/>
 *     &lt;enumeration value="218"/>
 *     &lt;enumeration value="219"/>
 *     &lt;enumeration value="220"/>
 *     &lt;enumeration value="221"/>
 *     &lt;enumeration value="222"/>
 *     &lt;enumeration value="223"/>
 *     &lt;enumeration value="224"/>
 *     &lt;enumeration value="225"/>
 *     &lt;enumeration value="226"/>
 *     &lt;enumeration value="227"/>
 *     &lt;enumeration value="228"/>
 *     &lt;enumeration value="229"/>
 *     &lt;enumeration value="230"/>
 *     &lt;enumeration value="231"/>
 *     &lt;enumeration value="232"/>
 *     &lt;enumeration value="233"/>
 *     &lt;enumeration value="234"/>
 *     &lt;enumeration value="235"/>
 *     &lt;enumeration value="236"/>
 *     &lt;enumeration value="237"/>
 *     &lt;enumeration value="238"/>
 *     &lt;enumeration value="239"/>
 *     &lt;enumeration value="240"/>
 *     &lt;enumeration value="241"/>
 *     &lt;enumeration value="242"/>
 *     &lt;enumeration value="243"/>
 *     &lt;enumeration value="244"/>
 *     &lt;enumeration value="245"/>
 *     &lt;enumeration value="246"/>
 *     &lt;enumeration value="247"/>
 *     &lt;enumeration value="248"/>
 *     &lt;enumeration value="249"/>
 *     &lt;enumeration value="250"/>
 *     &lt;enumeration value="251"/>
 *     &lt;enumeration value="252"/>
 *     &lt;enumeration value="253"/>
 *     &lt;enumeration value="254"/>
 *     &lt;enumeration value="255"/>
 *     &lt;enumeration value="256"/>
 *     &lt;enumeration value="257"/>
 *     &lt;enumeration value="258"/>
 *     &lt;enumeration value="259"/>
 *     &lt;enumeration value="260"/>
 *     &lt;enumeration value="261"/>
 *     &lt;enumeration value="262"/>
 *     &lt;enumeration value="263"/>
 *     &lt;enumeration value="264"/>
 *     &lt;enumeration value="265"/>
 *     &lt;enumeration value="266"/>
 *     &lt;enumeration value="267"/>
 *     &lt;enumeration value="268"/>
 *     &lt;enumeration value="269"/>
 *     &lt;enumeration value="270"/>
 *     &lt;enumeration value="271"/>
 *     &lt;enumeration value="272"/>
 *     &lt;enumeration value="273"/>
 *     &lt;enumeration value="274"/>
 *     &lt;enumeration value="275"/>
 *     &lt;enumeration value="276"/>
 *     &lt;enumeration value="277"/>
 *     &lt;enumeration value="278"/>
 *     &lt;enumeration value="279"/>
 *     &lt;enumeration value="280"/>
 *     &lt;enumeration value="281"/>
 *     &lt;enumeration value="282"/>
 *     &lt;enumeration value="283"/>
 *     &lt;enumeration value="284"/>
 *     &lt;enumeration value="285"/>
 *     &lt;enumeration value="286"/>
 *     &lt;enumeration value="287"/>
 *     &lt;enumeration value="288"/>
 *     &lt;enumeration value="289"/>
 *     &lt;enumeration value="290"/>
 *     &lt;enumeration value="291"/>
 *     &lt;enumeration value="292"/>
 *     &lt;enumeration value="293"/>
 *     &lt;enumeration value="294"/>
 *     &lt;enumeration value="295"/>
 *     &lt;enumeration value="296"/>
 *     &lt;enumeration value="297"/>
 *     &lt;enumeration value="298"/>
 *     &lt;enumeration value="299"/>
 *     &lt;enumeration value="300"/>
 *     &lt;enumeration value="301"/>
 *     &lt;enumeration value="302"/>
 *     &lt;enumeration value="303"/>
 *     &lt;enumeration value="304"/>
 *     &lt;enumeration value="305"/>
 *     &lt;enumeration value="306"/>
 *     &lt;enumeration value="307"/>
 *     &lt;enumeration value="308"/>
 *     &lt;enumeration value="309"/>
 *     &lt;enumeration value="310"/>
 *     &lt;enumeration value="311"/>
 *     &lt;enumeration value="312"/>
 *     &lt;enumeration value="313"/>
 *     &lt;enumeration value="314"/>
 *     &lt;enumeration value="315"/>
 *     &lt;enumeration value="316"/>
 *     &lt;enumeration value="317"/>
 *     &lt;enumeration value="318"/>
 *     &lt;enumeration value="319"/>
 *     &lt;enumeration value="320"/>
 *     &lt;enumeration value="321"/>
 *     &lt;enumeration value="322"/>
 *     &lt;enumeration value="323"/>
 *     &lt;enumeration value="324"/>
 *     &lt;enumeration value="325"/>
 *     &lt;enumeration value="326"/>
 *     &lt;enumeration value="327"/>
 *     &lt;enumeration value="328"/>
 *     &lt;enumeration value="329"/>
 *     &lt;enumeration value="330"/>
 *     &lt;enumeration value="331"/>
 *     &lt;enumeration value="332"/>
 *     &lt;enumeration value="333"/>
 *     &lt;enumeration value="334"/>
 *     &lt;enumeration value="335"/>
 *     &lt;enumeration value="336"/>
 *     &lt;enumeration value="337"/>
 *     &lt;enumeration value="338"/>
 *     &lt;enumeration value="339"/>
 *     &lt;enumeration value="340"/>
 *     &lt;enumeration value="341"/>
 *     &lt;enumeration value="342"/>
 *     &lt;enumeration value="343"/>
 *     &lt;enumeration value="344"/>
 *     &lt;enumeration value="345"/>
 *     &lt;enumeration value="346"/>
 *     &lt;enumeration value="347"/>
 *     &lt;enumeration value="348"/>
 *     &lt;enumeration value="349"/>
 *     &lt;enumeration value="350"/>
 *     &lt;enumeration value="351"/>
 *     &lt;enumeration value="352"/>
 *     &lt;enumeration value="353"/>
 *     &lt;enumeration value="354"/>
 *     &lt;enumeration value="355"/>
 *     &lt;enumeration value="356"/>
 *     &lt;enumeration value="357"/>
 *     &lt;enumeration value="358"/>
 *     &lt;enumeration value="359"/>
 *     &lt;enumeration value="360"/>
 *     &lt;enumeration value="361"/>
 *     &lt;enumeration value="362"/>
 *     &lt;enumeration value="363"/>
 *     &lt;enumeration value="364"/>
 *     &lt;enumeration value="365"/>
 *     &lt;enumeration value="366"/>
 *     &lt;enumeration value="367"/>
 *     &lt;enumeration value="368"/>
 *     &lt;enumeration value="369"/>
 *     &lt;enumeration value="370"/>
 *     &lt;enumeration value="371"/>
 *     &lt;enumeration value="372"/>
 *     &lt;enumeration value="373"/>
 *     &lt;enumeration value="374"/>
 *     &lt;enumeration value="375"/>
 *     &lt;enumeration value="376"/>
 *     &lt;enumeration value="377"/>
 *     &lt;enumeration value="378"/>
 *     &lt;enumeration value="379"/>
 *     &lt;enumeration value="380"/>
 *     &lt;enumeration value="381"/>
 *     &lt;enumeration value="382"/>
 *     &lt;enumeration value="383"/>
 *     &lt;enumeration value="384"/>
 *     &lt;enumeration value="385"/>
 *     &lt;enumeration value="386"/>
 *     &lt;enumeration value="387"/>
 *     &lt;enumeration value="388"/>
 *     &lt;enumeration value="389"/>
 *     &lt;enumeration value="390"/>
 *     &lt;enumeration value="391"/>
 *     &lt;enumeration value="392"/>
 *     &lt;enumeration value="393"/>
 *     &lt;enumeration value="394"/>
 *     &lt;enumeration value="395"/>
 *     &lt;enumeration value="396"/>
 *     &lt;enumeration value="397"/>
 *     &lt;enumeration value="398"/>
 *     &lt;enumeration value="399"/>
 *     &lt;enumeration value="400"/>
 *     &lt;enumeration value="401"/>
 *     &lt;enumeration value="402"/>
 *     &lt;enumeration value="403"/>
 *     &lt;enumeration value="404"/>
 *     &lt;enumeration value="405"/>
 *     &lt;enumeration value="406"/>
 *     &lt;enumeration value="407"/>
 *     &lt;enumeration value="408"/>
 *     &lt;enumeration value="409"/>
 *     &lt;enumeration value="410"/>
 *     &lt;enumeration value="411"/>
 *     &lt;enumeration value="412"/>
 *     &lt;enumeration value="413"/>
 *     &lt;enumeration value="414"/>
 *     &lt;enumeration value="415"/>
 *     &lt;enumeration value="416"/>
 *     &lt;enumeration value="417"/>
 *     &lt;enumeration value="418"/>
 *     &lt;enumeration value="419"/>
 *     &lt;enumeration value="420"/>
 *     &lt;enumeration value="421"/>
 *     &lt;enumeration value="422"/>
 *     &lt;enumeration value="423"/>
 *     &lt;enumeration value="424"/>
 *     &lt;enumeration value="425"/>
 *     &lt;enumeration value="426"/>
 *     &lt;enumeration value="427"/>
 *     &lt;enumeration value="428"/>
 *     &lt;enumeration value="429"/>
 *     &lt;enumeration value="430"/>
 *     &lt;enumeration value="431"/>
 *     &lt;enumeration value="432"/>
 *     &lt;enumeration value="433"/>
 *     &lt;enumeration value="434"/>
 *     &lt;enumeration value="435"/>
 *     &lt;enumeration value="436"/>
 *     &lt;enumeration value="437"/>
 *     &lt;enumeration value="438"/>
 *     &lt;enumeration value="439"/>
 *     &lt;enumeration value="440"/>
 *     &lt;enumeration value="441"/>
 *     &lt;enumeration value="442"/>
 *     &lt;enumeration value="443"/>
 *     &lt;enumeration value="444"/>
 *     &lt;enumeration value="445"/>
 *     &lt;enumeration value="446"/>
 *     &lt;enumeration value="447"/>
 *     &lt;enumeration value="448"/>
 *     &lt;enumeration value="449"/>
 *     &lt;enumeration value="450"/>
 *     &lt;enumeration value="451"/>
 *     &lt;enumeration value="452"/>
 *     &lt;enumeration value="453"/>
 *     &lt;enumeration value="454"/>
 *     &lt;enumeration value="455"/>
 *     &lt;enumeration value="456"/>
 *     &lt;enumeration value="457"/>
 *     &lt;enumeration value="458"/>
 *     &lt;enumeration value="459"/>
 *     &lt;enumeration value="460"/>
 *     &lt;enumeration value="461"/>
 *     &lt;enumeration value="462"/>
 *     &lt;enumeration value="463"/>
 *     &lt;enumeration value="464"/>
 *     &lt;enumeration value="465"/>
 *     &lt;enumeration value="466"/>
 *     &lt;enumeration value="467"/>
 *     &lt;enumeration value="468"/>
 *     &lt;enumeration value="469"/>
 *     &lt;enumeration value="470"/>
 *     &lt;enumeration value="471"/>
 *     &lt;enumeration value="472"/>
 *     &lt;enumeration value="473"/>
 *     &lt;enumeration value="474"/>
 *     &lt;enumeration value="475"/>
 *     &lt;enumeration value="476"/>
 *     &lt;enumeration value="477"/>
 *     &lt;enumeration value="478"/>
 *     &lt;enumeration value="479"/>
 *     &lt;enumeration value="480"/>
 *     &lt;enumeration value="481"/>
 *     &lt;enumeration value="482"/>
 *     &lt;enumeration value="483"/>
 *     &lt;enumeration value="484"/>
 *     &lt;enumeration value="485"/>
 *     &lt;enumeration value="486"/>
 *     &lt;enumeration value="487"/>
 *     &lt;enumeration value="488"/>
 *     &lt;enumeration value="489"/>
 *     &lt;enumeration value="490"/>
 *     &lt;enumeration value="491"/>
 *     &lt;enumeration value="492"/>
 *     &lt;enumeration value="493"/>
 *     &lt;enumeration value="494"/>
 *     &lt;enumeration value="495"/>
 *     &lt;enumeration value="496"/>
 *     &lt;enumeration value="497"/>
 *     &lt;enumeration value="498"/>
 *     &lt;enumeration value="499"/>
 *     &lt;enumeration value="500"/>
 *     &lt;enumeration value="501"/>
 *     &lt;enumeration value="502"/>
 *     &lt;enumeration value="503"/>
 *     &lt;enumeration value="504"/>
 *     &lt;enumeration value="505"/>
 *     &lt;enumeration value="506"/>
 *     &lt;enumeration value="507"/>
 *     &lt;enumeration value="508"/>
 *     &lt;enumeration value="509"/>
 *     &lt;enumeration value="510"/>
 *     &lt;enumeration value="511"/>
 *     &lt;enumeration value="512"/>
 *     &lt;enumeration value="513"/>
 *     &lt;enumeration value="514"/>
 *     &lt;enumeration value="515"/>
 *     &lt;enumeration value="516"/>
 *     &lt;enumeration value="517"/>
 *     &lt;enumeration value="518"/>
 *     &lt;enumeration value="519"/>
 *     &lt;enumeration value="520"/>
 *     &lt;enumeration value="521"/>
 *     &lt;enumeration value="522"/>
 *     &lt;enumeration value="523"/>
 *     &lt;enumeration value="524"/>
 *     &lt;enumeration value="525"/>
 *     &lt;enumeration value="526"/>
 *     &lt;enumeration value="527"/>
 *     &lt;enumeration value="528"/>
 *     &lt;enumeration value="529"/>
 *     &lt;enumeration value="530"/>
 *     &lt;enumeration value="531"/>
 *     &lt;enumeration value="532"/>
 *     &lt;enumeration value="533"/>
 *     &lt;enumeration value="534"/>
 *     &lt;enumeration value="535"/>
 *     &lt;enumeration value="536"/>
 *     &lt;enumeration value="537"/>
 *     &lt;enumeration value="538"/>
 *     &lt;enumeration value="539"/>
 *     &lt;enumeration value="540"/>
 *     &lt;enumeration value="541"/>
 *     &lt;enumeration value="542"/>
 *     &lt;enumeration value="543"/>
 *     &lt;enumeration value="544"/>
 *     &lt;enumeration value="545"/>
 *     &lt;enumeration value="546"/>
 *     &lt;enumeration value="547"/>
 *     &lt;enumeration value="548"/>
 *     &lt;enumeration value="549"/>
 *     &lt;enumeration value="550"/>
 *     &lt;enumeration value="551"/>
 *     &lt;enumeration value="552"/>
 *     &lt;enumeration value="553"/>
 *     &lt;enumeration value="554"/>
 *     &lt;enumeration value="555"/>
 *     &lt;enumeration value="556"/>
 *     &lt;enumeration value="557"/>
 *     &lt;enumeration value="558"/>
 *     &lt;enumeration value="559"/>
 *     &lt;enumeration value="560"/>
 *     &lt;enumeration value="561"/>
 *     &lt;enumeration value="562"/>
 *     &lt;enumeration value="563"/>
 *     &lt;enumeration value="564"/>
 *     &lt;enumeration value="565"/>
 *     &lt;enumeration value="566"/>
 *     &lt;enumeration value="567"/>
 *     &lt;enumeration value="568"/>
 *     &lt;enumeration value="569"/>
 *     &lt;enumeration value="570"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_Municipio", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")
@XmlEnum
public enum C_Municipio {

    @XmlEnumValue("001")
    VALUE_1("001"),
    @XmlEnumValue("002")
    VALUE_2("002"),
    @XmlEnumValue("003")
    VALUE_3("003"),
    @XmlEnumValue("004")
    VALUE_4("004"),
    @XmlEnumValue("005")
    VALUE_5("005"),
    @XmlEnumValue("006")
    VALUE_6("006"),
    @XmlEnumValue("007")
    VALUE_7("007"),
    @XmlEnumValue("008")
    VALUE_8("008"),
    @XmlEnumValue("009")
    VALUE_9("009"),
    @XmlEnumValue("010")
    VALUE_10("010"),
    @XmlEnumValue("011")
    VALUE_11("011"),
    @XmlEnumValue("012")
    VALUE_12("012"),
    @XmlEnumValue("013")
    VALUE_13("013"),
    @XmlEnumValue("014")
    VALUE_14("014"),
    @XmlEnumValue("015")
    VALUE_15("015"),
    @XmlEnumValue("016")
    VALUE_16("016"),
    @XmlEnumValue("017")
    VALUE_17("017"),
    @XmlEnumValue("018")
    VALUE_18("018"),
    @XmlEnumValue("019")
    VALUE_19("019"),
    @XmlEnumValue("020")
    VALUE_20("020"),
    @XmlEnumValue("021")
    VALUE_21("021"),
    @XmlEnumValue("022")
    VALUE_22("022"),
    @XmlEnumValue("023")
    VALUE_23("023"),
    @XmlEnumValue("024")
    VALUE_24("024"),
    @XmlEnumValue("025")
    VALUE_25("025"),
    @XmlEnumValue("026")
    VALUE_26("026"),
    @XmlEnumValue("027")
    VALUE_27("027"),
    @XmlEnumValue("028")
    VALUE_28("028"),
    @XmlEnumValue("029")
    VALUE_29("029"),
    @XmlEnumValue("030")
    VALUE_30("030"),
    @XmlEnumValue("031")
    VALUE_31("031"),
    @XmlEnumValue("032")
    VALUE_32("032"),
    @XmlEnumValue("033")
    VALUE_33("033"),
    @XmlEnumValue("034")
    VALUE_34("034"),
    @XmlEnumValue("035")
    VALUE_35("035"),
    @XmlEnumValue("036")
    VALUE_36("036"),
    @XmlEnumValue("037")
    VALUE_37("037"),
    @XmlEnumValue("038")
    VALUE_38("038"),
    @XmlEnumValue("039")
    VALUE_39("039"),
    @XmlEnumValue("040")
    VALUE_40("040"),
    @XmlEnumValue("041")
    VALUE_41("041"),
    @XmlEnumValue("042")
    VALUE_42("042"),
    @XmlEnumValue("043")
    VALUE_43("043"),
    @XmlEnumValue("044")
    VALUE_44("044"),
    @XmlEnumValue("045")
    VALUE_45("045"),
    @XmlEnumValue("046")
    VALUE_46("046"),
    @XmlEnumValue("047")
    VALUE_47("047"),
    @XmlEnumValue("048")
    VALUE_48("048"),
    @XmlEnumValue("049")
    VALUE_49("049"),
    @XmlEnumValue("050")
    VALUE_50("050"),
    @XmlEnumValue("051")
    VALUE_51("051"),
    @XmlEnumValue("052")
    VALUE_52("052"),
    @XmlEnumValue("053")
    VALUE_53("053"),
    @XmlEnumValue("054")
    VALUE_54("054"),
    @XmlEnumValue("055")
    VALUE_55("055"),
    @XmlEnumValue("056")
    VALUE_56("056"),
    @XmlEnumValue("057")
    VALUE_57("057"),
    @XmlEnumValue("058")
    VALUE_58("058"),
    @XmlEnumValue("059")
    VALUE_59("059"),
    @XmlEnumValue("060")
    VALUE_60("060"),
    @XmlEnumValue("061")
    VALUE_61("061"),
    @XmlEnumValue("062")
    VALUE_62("062"),
    @XmlEnumValue("063")
    VALUE_63("063"),
    @XmlEnumValue("064")
    VALUE_64("064"),
    @XmlEnumValue("065")
    VALUE_65("065"),
    @XmlEnumValue("066")
    VALUE_66("066"),
    @XmlEnumValue("067")
    VALUE_67("067"),
    @XmlEnumValue("068")
    VALUE_68("068"),
    @XmlEnumValue("069")
    VALUE_69("069"),
    @XmlEnumValue("070")
    VALUE_70("070"),
    @XmlEnumValue("071")
    VALUE_71("071"),
    @XmlEnumValue("072")
    VALUE_72("072"),
    @XmlEnumValue("073")
    VALUE_73("073"),
    @XmlEnumValue("074")
    VALUE_74("074"),
    @XmlEnumValue("075")
    VALUE_75("075"),
    @XmlEnumValue("076")
    VALUE_76("076"),
    @XmlEnumValue("077")
    VALUE_77("077"),
    @XmlEnumValue("078")
    VALUE_78("078"),
    @XmlEnumValue("079")
    VALUE_79("079"),
    @XmlEnumValue("080")
    VALUE_80("080"),
    @XmlEnumValue("081")
    VALUE_81("081"),
    @XmlEnumValue("082")
    VALUE_82("082"),
    @XmlEnumValue("083")
    VALUE_83("083"),
    @XmlEnumValue("084")
    VALUE_84("084"),
    @XmlEnumValue("085")
    VALUE_85("085"),
    @XmlEnumValue("086")
    VALUE_86("086"),
    @XmlEnumValue("087")
    VALUE_87("087"),
    @XmlEnumValue("088")
    VALUE_88("088"),
    @XmlEnumValue("089")
    VALUE_89("089"),
    @XmlEnumValue("090")
    VALUE_90("090"),
    @XmlEnumValue("091")
    VALUE_91("091"),
    @XmlEnumValue("092")
    VALUE_92("092"),
    @XmlEnumValue("093")
    VALUE_93("093"),
    @XmlEnumValue("094")
    VALUE_94("094"),
    @XmlEnumValue("095")
    VALUE_95("095"),
    @XmlEnumValue("096")
    VALUE_96("096"),
    @XmlEnumValue("097")
    VALUE_97("097"),
    @XmlEnumValue("098")
    VALUE_98("098"),
    @XmlEnumValue("099")
    VALUE_99("099"),
    @XmlEnumValue("100")
    VALUE_100("100"),
    @XmlEnumValue("101")
    VALUE_101("101"),
    @XmlEnumValue("102")
    VALUE_102("102"),
    @XmlEnumValue("103")
    VALUE_103("103"),
    @XmlEnumValue("104")
    VALUE_104("104"),
    @XmlEnumValue("105")
    VALUE_105("105"),
    @XmlEnumValue("106")
    VALUE_106("106"),
    @XmlEnumValue("107")
    VALUE_107("107"),
    @XmlEnumValue("108")
    VALUE_108("108"),
    @XmlEnumValue("109")
    VALUE_109("109"),
    @XmlEnumValue("110")
    VALUE_110("110"),
    @XmlEnumValue("111")
    VALUE_111("111"),
    @XmlEnumValue("112")
    VALUE_112("112"),
    @XmlEnumValue("113")
    VALUE_113("113"),
    @XmlEnumValue("114")
    VALUE_114("114"),
    @XmlEnumValue("115")
    VALUE_115("115"),
    @XmlEnumValue("116")
    VALUE_116("116"),
    @XmlEnumValue("117")
    VALUE_117("117"),
    @XmlEnumValue("118")
    VALUE_118("118"),
    @XmlEnumValue("119")
    VALUE_119("119"),
    @XmlEnumValue("120")
    VALUE_120("120"),
    @XmlEnumValue("121")
    VALUE_121("121"),
    @XmlEnumValue("122")
    VALUE_122("122"),
    @XmlEnumValue("123")
    VALUE_123("123"),
    @XmlEnumValue("124")
    VALUE_124("124"),
    @XmlEnumValue("125")
    VALUE_125("125"),
    @XmlEnumValue("126")
    VALUE_126("126"),
    @XmlEnumValue("127")
    VALUE_127("127"),
    @XmlEnumValue("128")
    VALUE_128("128"),
    @XmlEnumValue("129")
    VALUE_129("129"),
    @XmlEnumValue("130")
    VALUE_130("130"),
    @XmlEnumValue("131")
    VALUE_131("131"),
    @XmlEnumValue("132")
    VALUE_132("132"),
    @XmlEnumValue("133")
    VALUE_133("133"),
    @XmlEnumValue("134")
    VALUE_134("134"),
    @XmlEnumValue("135")
    VALUE_135("135"),
    @XmlEnumValue("136")
    VALUE_136("136"),
    @XmlEnumValue("137")
    VALUE_137("137"),
    @XmlEnumValue("138")
    VALUE_138("138"),
    @XmlEnumValue("139")
    VALUE_139("139"),
    @XmlEnumValue("140")
    VALUE_140("140"),
    @XmlEnumValue("141")
    VALUE_141("141"),
    @XmlEnumValue("142")
    VALUE_142("142"),
    @XmlEnumValue("143")
    VALUE_143("143"),
    @XmlEnumValue("144")
    VALUE_144("144"),
    @XmlEnumValue("145")
    VALUE_145("145"),
    @XmlEnumValue("146")
    VALUE_146("146"),
    @XmlEnumValue("147")
    VALUE_147("147"),
    @XmlEnumValue("148")
    VALUE_148("148"),
    @XmlEnumValue("149")
    VALUE_149("149"),
    @XmlEnumValue("150")
    VALUE_150("150"),
    @XmlEnumValue("151")
    VALUE_151("151"),
    @XmlEnumValue("152")
    VALUE_152("152"),
    @XmlEnumValue("153")
    VALUE_153("153"),
    @XmlEnumValue("154")
    VALUE_154("154"),
    @XmlEnumValue("155")
    VALUE_155("155"),
    @XmlEnumValue("156")
    VALUE_156("156"),
    @XmlEnumValue("157")
    VALUE_157("157"),
    @XmlEnumValue("158")
    VALUE_158("158"),
    @XmlEnumValue("159")
    VALUE_159("159"),
    @XmlEnumValue("160")
    VALUE_160("160"),
    @XmlEnumValue("161")
    VALUE_161("161"),
    @XmlEnumValue("162")
    VALUE_162("162"),
    @XmlEnumValue("163")
    VALUE_163("163"),
    @XmlEnumValue("164")
    VALUE_164("164"),
    @XmlEnumValue("165")
    VALUE_165("165"),
    @XmlEnumValue("166")
    VALUE_166("166"),
    @XmlEnumValue("167")
    VALUE_167("167"),
    @XmlEnumValue("168")
    VALUE_168("168"),
    @XmlEnumValue("169")
    VALUE_169("169"),
    @XmlEnumValue("170")
    VALUE_170("170"),
    @XmlEnumValue("171")
    VALUE_171("171"),
    @XmlEnumValue("172")
    VALUE_172("172"),
    @XmlEnumValue("173")
    VALUE_173("173"),
    @XmlEnumValue("174")
    VALUE_174("174"),
    @XmlEnumValue("175")
    VALUE_175("175"),
    @XmlEnumValue("176")
    VALUE_176("176"),
    @XmlEnumValue("177")
    VALUE_177("177"),
    @XmlEnumValue("178")
    VALUE_178("178"),
    @XmlEnumValue("179")
    VALUE_179("179"),
    @XmlEnumValue("180")
    VALUE_180("180"),
    @XmlEnumValue("181")
    VALUE_181("181"),
    @XmlEnumValue("182")
    VALUE_182("182"),
    @XmlEnumValue("183")
    VALUE_183("183"),
    @XmlEnumValue("184")
    VALUE_184("184"),
    @XmlEnumValue("185")
    VALUE_185("185"),
    @XmlEnumValue("186")
    VALUE_186("186"),
    @XmlEnumValue("187")
    VALUE_187("187"),
    @XmlEnumValue("188")
    VALUE_188("188"),
    @XmlEnumValue("189")
    VALUE_189("189"),
    @XmlEnumValue("190")
    VALUE_190("190"),
    @XmlEnumValue("191")
    VALUE_191("191"),
    @XmlEnumValue("192")
    VALUE_192("192"),
    @XmlEnumValue("193")
    VALUE_193("193"),
    @XmlEnumValue("194")
    VALUE_194("194"),
    @XmlEnumValue("195")
    VALUE_195("195"),
    @XmlEnumValue("196")
    VALUE_196("196"),
    @XmlEnumValue("197")
    VALUE_197("197"),
    @XmlEnumValue("198")
    VALUE_198("198"),
    @XmlEnumValue("199")
    VALUE_199("199"),
    @XmlEnumValue("200")
    VALUE_200("200"),
    @XmlEnumValue("201")
    VALUE_201("201"),
    @XmlEnumValue("202")
    VALUE_202("202"),
    @XmlEnumValue("203")
    VALUE_203("203"),
    @XmlEnumValue("204")
    VALUE_204("204"),
    @XmlEnumValue("205")
    VALUE_205("205"),
    @XmlEnumValue("206")
    VALUE_206("206"),
    @XmlEnumValue("207")
    VALUE_207("207"),
    @XmlEnumValue("208")
    VALUE_208("208"),
    @XmlEnumValue("209")
    VALUE_209("209"),
    @XmlEnumValue("210")
    VALUE_210("210"),
    @XmlEnumValue("211")
    VALUE_211("211"),
    @XmlEnumValue("212")
    VALUE_212("212"),
    @XmlEnumValue("213")
    VALUE_213("213"),
    @XmlEnumValue("214")
    VALUE_214("214"),
    @XmlEnumValue("215")
    VALUE_215("215"),
    @XmlEnumValue("216")
    VALUE_216("216"),
    @XmlEnumValue("217")
    VALUE_217("217"),
    @XmlEnumValue("218")
    VALUE_218("218"),
    @XmlEnumValue("219")
    VALUE_219("219"),
    @XmlEnumValue("220")
    VALUE_220("220"),
    @XmlEnumValue("221")
    VALUE_221("221"),
    @XmlEnumValue("222")
    VALUE_222("222"),
    @XmlEnumValue("223")
    VALUE_223("223"),
    @XmlEnumValue("224")
    VALUE_224("224"),
    @XmlEnumValue("225")
    VALUE_225("225"),
    @XmlEnumValue("226")
    VALUE_226("226"),
    @XmlEnumValue("227")
    VALUE_227("227"),
    @XmlEnumValue("228")
    VALUE_228("228"),
    @XmlEnumValue("229")
    VALUE_229("229"),
    @XmlEnumValue("230")
    VALUE_230("230"),
    @XmlEnumValue("231")
    VALUE_231("231"),
    @XmlEnumValue("232")
    VALUE_232("232"),
    @XmlEnumValue("233")
    VALUE_233("233"),
    @XmlEnumValue("234")
    VALUE_234("234"),
    @XmlEnumValue("235")
    VALUE_235("235"),
    @XmlEnumValue("236")
    VALUE_236("236"),
    @XmlEnumValue("237")
    VALUE_237("237"),
    @XmlEnumValue("238")
    VALUE_238("238"),
    @XmlEnumValue("239")
    VALUE_239("239"),
    @XmlEnumValue("240")
    VALUE_240("240"),
    @XmlEnumValue("241")
    VALUE_241("241"),
    @XmlEnumValue("242")
    VALUE_242("242"),
    @XmlEnumValue("243")
    VALUE_243("243"),
    @XmlEnumValue("244")
    VALUE_244("244"),
    @XmlEnumValue("245")
    VALUE_245("245"),
    @XmlEnumValue("246")
    VALUE_246("246"),
    @XmlEnumValue("247")
    VALUE_247("247"),
    @XmlEnumValue("248")
    VALUE_248("248"),
    @XmlEnumValue("249")
    VALUE_249("249"),
    @XmlEnumValue("250")
    VALUE_250("250"),
    @XmlEnumValue("251")
    VALUE_251("251"),
    @XmlEnumValue("252")
    VALUE_252("252"),
    @XmlEnumValue("253")
    VALUE_253("253"),
    @XmlEnumValue("254")
    VALUE_254("254"),
    @XmlEnumValue("255")
    VALUE_255("255"),
    @XmlEnumValue("256")
    VALUE_256("256"),
    @XmlEnumValue("257")
    VALUE_257("257"),
    @XmlEnumValue("258")
    VALUE_258("258"),
    @XmlEnumValue("259")
    VALUE_259("259"),
    @XmlEnumValue("260")
    VALUE_260("260"),
    @XmlEnumValue("261")
    VALUE_261("261"),
    @XmlEnumValue("262")
    VALUE_262("262"),
    @XmlEnumValue("263")
    VALUE_263("263"),
    @XmlEnumValue("264")
    VALUE_264("264"),
    @XmlEnumValue("265")
    VALUE_265("265"),
    @XmlEnumValue("266")
    VALUE_266("266"),
    @XmlEnumValue("267")
    VALUE_267("267"),
    @XmlEnumValue("268")
    VALUE_268("268"),
    @XmlEnumValue("269")
    VALUE_269("269"),
    @XmlEnumValue("270")
    VALUE_270("270"),
    @XmlEnumValue("271")
    VALUE_271("271"),
    @XmlEnumValue("272")
    VALUE_272("272"),
    @XmlEnumValue("273")
    VALUE_273("273"),
    @XmlEnumValue("274")
    VALUE_274("274"),
    @XmlEnumValue("275")
    VALUE_275("275"),
    @XmlEnumValue("276")
    VALUE_276("276"),
    @XmlEnumValue("277")
    VALUE_277("277"),
    @XmlEnumValue("278")
    VALUE_278("278"),
    @XmlEnumValue("279")
    VALUE_279("279"),
    @XmlEnumValue("280")
    VALUE_280("280"),
    @XmlEnumValue("281")
    VALUE_281("281"),
    @XmlEnumValue("282")
    VALUE_282("282"),
    @XmlEnumValue("283")
    VALUE_283("283"),
    @XmlEnumValue("284")
    VALUE_284("284"),
    @XmlEnumValue("285")
    VALUE_285("285"),
    @XmlEnumValue("286")
    VALUE_286("286"),
    @XmlEnumValue("287")
    VALUE_287("287"),
    @XmlEnumValue("288")
    VALUE_288("288"),
    @XmlEnumValue("289")
    VALUE_289("289"),
    @XmlEnumValue("290")
    VALUE_290("290"),
    @XmlEnumValue("291")
    VALUE_291("291"),
    @XmlEnumValue("292")
    VALUE_292("292"),
    @XmlEnumValue("293")
    VALUE_293("293"),
    @XmlEnumValue("294")
    VALUE_294("294"),
    @XmlEnumValue("295")
    VALUE_295("295"),
    @XmlEnumValue("296")
    VALUE_296("296"),
    @XmlEnumValue("297")
    VALUE_297("297"),
    @XmlEnumValue("298")
    VALUE_298("298"),
    @XmlEnumValue("299")
    VALUE_299("299"),
    @XmlEnumValue("300")
    VALUE_300("300"),
    @XmlEnumValue("301")
    VALUE_301("301"),
    @XmlEnumValue("302")
    VALUE_302("302"),
    @XmlEnumValue("303")
    VALUE_303("303"),
    @XmlEnumValue("304")
    VALUE_304("304"),
    @XmlEnumValue("305")
    VALUE_305("305"),
    @XmlEnumValue("306")
    VALUE_306("306"),
    @XmlEnumValue("307")
    VALUE_307("307"),
    @XmlEnumValue("308")
    VALUE_308("308"),
    @XmlEnumValue("309")
    VALUE_309("309"),
    @XmlEnumValue("310")
    VALUE_310("310"),
    @XmlEnumValue("311")
    VALUE_311("311"),
    @XmlEnumValue("312")
    VALUE_312("312"),
    @XmlEnumValue("313")
    VALUE_313("313"),
    @XmlEnumValue("314")
    VALUE_314("314"),
    @XmlEnumValue("315")
    VALUE_315("315"),
    @XmlEnumValue("316")
    VALUE_316("316"),
    @XmlEnumValue("317")
    VALUE_317("317"),
    @XmlEnumValue("318")
    VALUE_318("318"),
    @XmlEnumValue("319")
    VALUE_319("319"),
    @XmlEnumValue("320")
    VALUE_320("320"),
    @XmlEnumValue("321")
    VALUE_321("321"),
    @XmlEnumValue("322")
    VALUE_322("322"),
    @XmlEnumValue("323")
    VALUE_323("323"),
    @XmlEnumValue("324")
    VALUE_324("324"),
    @XmlEnumValue("325")
    VALUE_325("325"),
    @XmlEnumValue("326")
    VALUE_326("326"),
    @XmlEnumValue("327")
    VALUE_327("327"),
    @XmlEnumValue("328")
    VALUE_328("328"),
    @XmlEnumValue("329")
    VALUE_329("329"),
    @XmlEnumValue("330")
    VALUE_330("330"),
    @XmlEnumValue("331")
    VALUE_331("331"),
    @XmlEnumValue("332")
    VALUE_332("332"),
    @XmlEnumValue("333")
    VALUE_333("333"),
    @XmlEnumValue("334")
    VALUE_334("334"),
    @XmlEnumValue("335")
    VALUE_335("335"),
    @XmlEnumValue("336")
    VALUE_336("336"),
    @XmlEnumValue("337")
    VALUE_337("337"),
    @XmlEnumValue("338")
    VALUE_338("338"),
    @XmlEnumValue("339")
    VALUE_339("339"),
    @XmlEnumValue("340")
    VALUE_340("340"),
    @XmlEnumValue("341")
    VALUE_341("341"),
    @XmlEnumValue("342")
    VALUE_342("342"),
    @XmlEnumValue("343")
    VALUE_343("343"),
    @XmlEnumValue("344")
    VALUE_344("344"),
    @XmlEnumValue("345")
    VALUE_345("345"),
    @XmlEnumValue("346")
    VALUE_346("346"),
    @XmlEnumValue("347")
    VALUE_347("347"),
    @XmlEnumValue("348")
    VALUE_348("348"),
    @XmlEnumValue("349")
    VALUE_349("349"),
    @XmlEnumValue("350")
    VALUE_350("350"),
    @XmlEnumValue("351")
    VALUE_351("351"),
    @XmlEnumValue("352")
    VALUE_352("352"),
    @XmlEnumValue("353")
    VALUE_353("353"),
    @XmlEnumValue("354")
    VALUE_354("354"),
    @XmlEnumValue("355")
    VALUE_355("355"),
    @XmlEnumValue("356")
    VALUE_356("356"),
    @XmlEnumValue("357")
    VALUE_357("357"),
    @XmlEnumValue("358")
    VALUE_358("358"),
    @XmlEnumValue("359")
    VALUE_359("359"),
    @XmlEnumValue("360")
    VALUE_360("360"),
    @XmlEnumValue("361")
    VALUE_361("361"),
    @XmlEnumValue("362")
    VALUE_362("362"),
    @XmlEnumValue("363")
    VALUE_363("363"),
    @XmlEnumValue("364")
    VALUE_364("364"),
    @XmlEnumValue("365")
    VALUE_365("365"),
    @XmlEnumValue("366")
    VALUE_366("366"),
    @XmlEnumValue("367")
    VALUE_367("367"),
    @XmlEnumValue("368")
    VALUE_368("368"),
    @XmlEnumValue("369")
    VALUE_369("369"),
    @XmlEnumValue("370")
    VALUE_370("370"),
    @XmlEnumValue("371")
    VALUE_371("371"),
    @XmlEnumValue("372")
    VALUE_372("372"),
    @XmlEnumValue("373")
    VALUE_373("373"),
    @XmlEnumValue("374")
    VALUE_374("374"),
    @XmlEnumValue("375")
    VALUE_375("375"),
    @XmlEnumValue("376")
    VALUE_376("376"),
    @XmlEnumValue("377")
    VALUE_377("377"),
    @XmlEnumValue("378")
    VALUE_378("378"),
    @XmlEnumValue("379")
    VALUE_379("379"),
    @XmlEnumValue("380")
    VALUE_380("380"),
    @XmlEnumValue("381")
    VALUE_381("381"),
    @XmlEnumValue("382")
    VALUE_382("382"),
    @XmlEnumValue("383")
    VALUE_383("383"),
    @XmlEnumValue("384")
    VALUE_384("384"),
    @XmlEnumValue("385")
    VALUE_385("385"),
    @XmlEnumValue("386")
    VALUE_386("386"),
    @XmlEnumValue("387")
    VALUE_387("387"),
    @XmlEnumValue("388")
    VALUE_388("388"),
    @XmlEnumValue("389")
    VALUE_389("389"),
    @XmlEnumValue("390")
    VALUE_390("390"),
    @XmlEnumValue("391")
    VALUE_391("391"),
    @XmlEnumValue("392")
    VALUE_392("392"),
    @XmlEnumValue("393")
    VALUE_393("393"),
    @XmlEnumValue("394")
    VALUE_394("394"),
    @XmlEnumValue("395")
    VALUE_395("395"),
    @XmlEnumValue("396")
    VALUE_396("396"),
    @XmlEnumValue("397")
    VALUE_397("397"),
    @XmlEnumValue("398")
    VALUE_398("398"),
    @XmlEnumValue("399")
    VALUE_399("399"),
    @XmlEnumValue("400")
    VALUE_400("400"),
    @XmlEnumValue("401")
    VALUE_401("401"),
    @XmlEnumValue("402")
    VALUE_402("402"),
    @XmlEnumValue("403")
    VALUE_403("403"),
    @XmlEnumValue("404")
    VALUE_404("404"),
    @XmlEnumValue("405")
    VALUE_405("405"),
    @XmlEnumValue("406")
    VALUE_406("406"),
    @XmlEnumValue("407")
    VALUE_407("407"),
    @XmlEnumValue("408")
    VALUE_408("408"),
    @XmlEnumValue("409")
    VALUE_409("409"),
    @XmlEnumValue("410")
    VALUE_410("410"),
    @XmlEnumValue("411")
    VALUE_411("411"),
    @XmlEnumValue("412")
    VALUE_412("412"),
    @XmlEnumValue("413")
    VALUE_413("413"),
    @XmlEnumValue("414")
    VALUE_414("414"),
    @XmlEnumValue("415")
    VALUE_415("415"),
    @XmlEnumValue("416")
    VALUE_416("416"),
    @XmlEnumValue("417")
    VALUE_417("417"),
    @XmlEnumValue("418")
    VALUE_418("418"),
    @XmlEnumValue("419")
    VALUE_419("419"),
    @XmlEnumValue("420")
    VALUE_420("420"),
    @XmlEnumValue("421")
    VALUE_421("421"),
    @XmlEnumValue("422")
    VALUE_422("422"),
    @XmlEnumValue("423")
    VALUE_423("423"),
    @XmlEnumValue("424")
    VALUE_424("424"),
    @XmlEnumValue("425")
    VALUE_425("425"),
    @XmlEnumValue("426")
    VALUE_426("426"),
    @XmlEnumValue("427")
    VALUE_427("427"),
    @XmlEnumValue("428")
    VALUE_428("428"),
    @XmlEnumValue("429")
    VALUE_429("429"),
    @XmlEnumValue("430")
    VALUE_430("430"),
    @XmlEnumValue("431")
    VALUE_431("431"),
    @XmlEnumValue("432")
    VALUE_432("432"),
    @XmlEnumValue("433")
    VALUE_433("433"),
    @XmlEnumValue("434")
    VALUE_434("434"),
    @XmlEnumValue("435")
    VALUE_435("435"),
    @XmlEnumValue("436")
    VALUE_436("436"),
    @XmlEnumValue("437")
    VALUE_437("437"),
    @XmlEnumValue("438")
    VALUE_438("438"),
    @XmlEnumValue("439")
    VALUE_439("439"),
    @XmlEnumValue("440")
    VALUE_440("440"),
    @XmlEnumValue("441")
    VALUE_441("441"),
    @XmlEnumValue("442")
    VALUE_442("442"),
    @XmlEnumValue("443")
    VALUE_443("443"),
    @XmlEnumValue("444")
    VALUE_444("444"),
    @XmlEnumValue("445")
    VALUE_445("445"),
    @XmlEnumValue("446")
    VALUE_446("446"),
    @XmlEnumValue("447")
    VALUE_447("447"),
    @XmlEnumValue("448")
    VALUE_448("448"),
    @XmlEnumValue("449")
    VALUE_449("449"),
    @XmlEnumValue("450")
    VALUE_450("450"),
    @XmlEnumValue("451")
    VALUE_451("451"),
    @XmlEnumValue("452")
    VALUE_452("452"),
    @XmlEnumValue("453")
    VALUE_453("453"),
    @XmlEnumValue("454")
    VALUE_454("454"),
    @XmlEnumValue("455")
    VALUE_455("455"),
    @XmlEnumValue("456")
    VALUE_456("456"),
    @XmlEnumValue("457")
    VALUE_457("457"),
    @XmlEnumValue("458")
    VALUE_458("458"),
    @XmlEnumValue("459")
    VALUE_459("459"),
    @XmlEnumValue("460")
    VALUE_460("460"),
    @XmlEnumValue("461")
    VALUE_461("461"),
    @XmlEnumValue("462")
    VALUE_462("462"),
    @XmlEnumValue("463")
    VALUE_463("463"),
    @XmlEnumValue("464")
    VALUE_464("464"),
    @XmlEnumValue("465")
    VALUE_465("465"),
    @XmlEnumValue("466")
    VALUE_466("466"),
    @XmlEnumValue("467")
    VALUE_467("467"),
    @XmlEnumValue("468")
    VALUE_468("468"),
    @XmlEnumValue("469")
    VALUE_469("469"),
    @XmlEnumValue("470")
    VALUE_470("470"),
    @XmlEnumValue("471")
    VALUE_471("471"),
    @XmlEnumValue("472")
    VALUE_472("472"),
    @XmlEnumValue("473")
    VALUE_473("473"),
    @XmlEnumValue("474")
    VALUE_474("474"),
    @XmlEnumValue("475")
    VALUE_475("475"),
    @XmlEnumValue("476")
    VALUE_476("476"),
    @XmlEnumValue("477")
    VALUE_477("477"),
    @XmlEnumValue("478")
    VALUE_478("478"),
    @XmlEnumValue("479")
    VALUE_479("479"),
    @XmlEnumValue("480")
    VALUE_480("480"),
    @XmlEnumValue("481")
    VALUE_481("481"),
    @XmlEnumValue("482")
    VALUE_482("482"),
    @XmlEnumValue("483")
    VALUE_483("483"),
    @XmlEnumValue("484")
    VALUE_484("484"),
    @XmlEnumValue("485")
    VALUE_485("485"),
    @XmlEnumValue("486")
    VALUE_486("486"),
    @XmlEnumValue("487")
    VALUE_487("487"),
    @XmlEnumValue("488")
    VALUE_488("488"),
    @XmlEnumValue("489")
    VALUE_489("489"),
    @XmlEnumValue("490")
    VALUE_490("490"),
    @XmlEnumValue("491")
    VALUE_491("491"),
    @XmlEnumValue("492")
    VALUE_492("492"),
    @XmlEnumValue("493")
    VALUE_493("493"),
    @XmlEnumValue("494")
    VALUE_494("494"),
    @XmlEnumValue("495")
    VALUE_495("495"),
    @XmlEnumValue("496")
    VALUE_496("496"),
    @XmlEnumValue("497")
    VALUE_497("497"),
    @XmlEnumValue("498")
    VALUE_498("498"),
    @XmlEnumValue("499")
    VALUE_499("499"),
    @XmlEnumValue("500")
    VALUE_500("500"),
    @XmlEnumValue("501")
    VALUE_501("501"),
    @XmlEnumValue("502")
    VALUE_502("502"),
    @XmlEnumValue("503")
    VALUE_503("503"),
    @XmlEnumValue("504")
    VALUE_504("504"),
    @XmlEnumValue("505")
    VALUE_505("505"),
    @XmlEnumValue("506")
    VALUE_506("506"),
    @XmlEnumValue("507")
    VALUE_507("507"),
    @XmlEnumValue("508")
    VALUE_508("508"),
    @XmlEnumValue("509")
    VALUE_509("509"),
    @XmlEnumValue("510")
    VALUE_510("510"),
    @XmlEnumValue("511")
    VALUE_511("511"),
    @XmlEnumValue("512")
    VALUE_512("512"),
    @XmlEnumValue("513")
    VALUE_513("513"),
    @XmlEnumValue("514")
    VALUE_514("514"),
    @XmlEnumValue("515")
    VALUE_515("515"),
    @XmlEnumValue("516")
    VALUE_516("516"),
    @XmlEnumValue("517")
    VALUE_517("517"),
    @XmlEnumValue("518")
    VALUE_518("518"),
    @XmlEnumValue("519")
    VALUE_519("519"),
    @XmlEnumValue("520")
    VALUE_520("520"),
    @XmlEnumValue("521")
    VALUE_521("521"),
    @XmlEnumValue("522")
    VALUE_522("522"),
    @XmlEnumValue("523")
    VALUE_523("523"),
    @XmlEnumValue("524")
    VALUE_524("524"),
    @XmlEnumValue("525")
    VALUE_525("525"),
    @XmlEnumValue("526")
    VALUE_526("526"),
    @XmlEnumValue("527")
    VALUE_527("527"),
    @XmlEnumValue("528")
    VALUE_528("528"),
    @XmlEnumValue("529")
    VALUE_529("529"),
    @XmlEnumValue("530")
    VALUE_530("530"),
    @XmlEnumValue("531")
    VALUE_531("531"),
    @XmlEnumValue("532")
    VALUE_532("532"),
    @XmlEnumValue("533")
    VALUE_533("533"),
    @XmlEnumValue("534")
    VALUE_534("534"),
    @XmlEnumValue("535")
    VALUE_535("535"),
    @XmlEnumValue("536")
    VALUE_536("536"),
    @XmlEnumValue("537")
    VALUE_537("537"),
    @XmlEnumValue("538")
    VALUE_538("538"),
    @XmlEnumValue("539")
    VALUE_539("539"),
    @XmlEnumValue("540")
    VALUE_540("540"),
    @XmlEnumValue("541")
    VALUE_541("541"),
    @XmlEnumValue("542")
    VALUE_542("542"),
    @XmlEnumValue("543")
    VALUE_543("543"),
    @XmlEnumValue("544")
    VALUE_544("544"),
    @XmlEnumValue("545")
    VALUE_545("545"),
    @XmlEnumValue("546")
    VALUE_546("546"),
    @XmlEnumValue("547")
    VALUE_547("547"),
    @XmlEnumValue("548")
    VALUE_548("548"),
    @XmlEnumValue("549")
    VALUE_549("549"),
    @XmlEnumValue("550")
    VALUE_550("550"),
    @XmlEnumValue("551")
    VALUE_551("551"),
    @XmlEnumValue("552")
    VALUE_552("552"),
    @XmlEnumValue("553")
    VALUE_553("553"),
    @XmlEnumValue("554")
    VALUE_554("554"),
    @XmlEnumValue("555")
    VALUE_555("555"),
    @XmlEnumValue("556")
    VALUE_556("556"),
    @XmlEnumValue("557")
    VALUE_557("557"),
    @XmlEnumValue("558")
    VALUE_558("558"),
    @XmlEnumValue("559")
    VALUE_559("559"),
    @XmlEnumValue("560")
    VALUE_560("560"),
    @XmlEnumValue("561")
    VALUE_561("561"),
    @XmlEnumValue("562")
    VALUE_562("562"),
    @XmlEnumValue("563")
    VALUE_563("563"),
    @XmlEnumValue("564")
    VALUE_564("564"),
    @XmlEnumValue("565")
    VALUE_565("565"),
    @XmlEnumValue("566")
    VALUE_566("566"),
    @XmlEnumValue("567")
    VALUE_567("567"),
    @XmlEnumValue("568")
    VALUE_568("568"),
    @XmlEnumValue("569")
    VALUE_569("569"),
    @XmlEnumValue("570")
    VALUE_570("570");
    private final String value;

    C_Municipio(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_Municipio fromValue(String v) {
        for (C_Municipio c: C_Municipio.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
