//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 09:45:50 AM CDT 
//


package com.tikal.cacao.sat.cfd.catalogos;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for c_RegimenFiscal.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="c_RegimenFiscal">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;whiteSpace value="collapse"/>
 *     &lt;enumeration value="601"/>
 *     &lt;enumeration value="603"/>
 *     &lt;enumeration value="605"/>
 *     &lt;enumeration value="606"/>
 *     &lt;enumeration value="608"/>
 *     &lt;enumeration value="609"/>
 *     &lt;enumeration value="610"/>
 *     &lt;enumeration value="611"/>
 *     &lt;enumeration value="612"/>
 *     &lt;enumeration value="614"/>
 *     &lt;enumeration value="616"/>
 *     &lt;enumeration value="620"/>
 *     &lt;enumeration value="621"/>
 *     &lt;enumeration value="622"/>
 *     &lt;enumeration value="623"/>
 *     &lt;enumeration value="624"/>
 *     &lt;enumeration value="628"/>
 *     &lt;enumeration value="607"/>
 *     &lt;enumeration value="629"/>
 *     &lt;enumeration value="630"/>
 *     &lt;enumeration value="615"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "c_RegimenFiscal", namespace = "http://www.sat.gob.mx/sitio_internet/cfd/catalogos")
@XmlEnum
public enum C_RegimenFiscal {

    @XmlEnumValue("601")
    VALUE_1("601"),
    @XmlEnumValue("603")
    VALUE_2("603"),
    @XmlEnumValue("605")
    VALUE_3("605"),
    @XmlEnumValue("606")
    VALUE_4("606"),
    @XmlEnumValue("608")
    VALUE_5("608"),
    @XmlEnumValue("609")
    VALUE_6("609"),
    @XmlEnumValue("610")
    VALUE_7("610"),
    @XmlEnumValue("611")
    VALUE_8("611"),
    @XmlEnumValue("612")
    VALUE_9("612"),
    @XmlEnumValue("614")
    VALUE_10("614"),
    @XmlEnumValue("616")
    VALUE_11("616"),
    @XmlEnumValue("620")
    VALUE_12("620"),
    @XmlEnumValue("621")
    VALUE_13("621"),
    @XmlEnumValue("622")
    VALUE_14("622"),
    @XmlEnumValue("623")
    VALUE_15("623"),
    @XmlEnumValue("624")
    VALUE_16("624"),
    @XmlEnumValue("628")
    VALUE_17("628"),
    @XmlEnumValue("607")
    VALUE_18("607"),
    @XmlEnumValue("629")
    VALUE_19("629"),
    @XmlEnumValue("630")
    VALUE_20("630"),
    @XmlEnumValue("615")
    VALUE_21("615");
    private final String value;

    C_RegimenFiscal(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static C_RegimenFiscal fromValue(String v) {
        for (C_RegimenFiscal c: C_RegimenFiscal.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
