//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.23 at 09:45:50 AM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.sat.gob.mx/cfd/3",
xmlns = {
		@javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.sat.gob.mx/cfd/3", prefix="cfdi")
},
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tikal.cacao.sat.cfd33;
